WINNER = 69
MIN = 0
MAX = 1000
PROBABILTY_OF_MUTATION = 50  # %
MUTATION_APLITUDE = 0.3
PRECISION = 4
# how many generations
MAX_RECURSION_ITERATIONS = 50

SIZE_OF_POPULATION = 60
SIZE_OF_BEST_SQUAD = 1
BESTER_MULTIPLIER = 60

FIXED_INITIAL_POPULATION = 0

LOGING_CHANGE_NUMBER = 0
LOGGING_AVERAGE_OF_POPULATION = 1
LOGGING_WHOLE_POPULATION_AFTER_EACH_ITERATION = 1
LOGGIN_BEST_SQUAD = 1
LOGGIN_POPULATION_POINTS = 0