WINNER = 69
MIN = 0
MAX = 1000
PROBABILTY_OF_MUTATION = 20  # %
MUTATION_APLITUDE = 0.5

# how many generations
MAX_RECURSION_ITERATIONS = 5000

SIZE_OF_POPULATION = 100
SIZE_OF_BEST_SQUAD = 5
BESTER_MULTIPLIER = 20

FIXED_INITIAL_POPULATION = 1

LOGING_CHANGE_NUMBER = 0
LOGGING_AVERAGE_OF_POPULATION = 1
LOGGING_WHOLE_POPULATION_AFTER_EACH_ITERATION = 0